language: ruby

os:
  - osx
  - linux

rvm:
  - "2.4"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --assume-yes --quiet gcc-multilib; fi

install:
  - bundle install
  - gem install rspec
  - gem install rubocop -v 0.57.2

script:
  - cd test && rake ci
  - cd ..
  - cd examples && cd make_example
  - make clean
  - make setup
  - make test
  - cd ..
  - cd temp_sensor
  - rake ci
